#ifndef PDGENUMS_H_
#define PDGENUMS_H_

namespace pdg
{
  enum class EdgeType
  {
    CONTROLDEP_CALLINV,
    CONTROLDEP_CALLRET,
    CONTROLDEP_ENTRY,
    CONTROLDEP_BR,
    CONTROLDEP_OTHER,
    DATA_DEF_USE,
    DATA_RAW,
    DATA_RET,
    DATA_ALIAS,
    PARAMETER_IN,
    PARAMETER_OUT,
    PARAMETER_FIELD,
    ANNO_VAR,
    ANNO_GLOBAL,
    ANNO_OTHER,

    IND_CALL,
    GLOBAL_DEP,
    TYPE_OTHEREDGE

  };

  enum class GraphNodeType
  {
    INST_FUNCALL,
    INST_RET,
    INST_BR,
    INST_OTHER,
    VAR_STATICALLOCGLOBALSCOPE,
    VAR_STATICALLOCMODULESCOPE,
    VAR_STATICALLOCFUNCTIONSCOPE,
    VAR_OTHER,
    FUNC_ENTRY,
    PARAM_FORMALIN,
    PARAM_FORMALOUT,
    PARAM_ACTUALIN,
    PARAM_ACTUALOUT,
    ANNO_VAR,
    ANNO_GLOBAL,
    ANNO_OTHER,
    FUNC
  };

  enum class AccessTag
  {
    DATA_READ,
    DATA_WRITE
  };
}

#endif